version: '3'

services:
  postgres:
    container_name: api-solid-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitenode03

  cache:
    container_name: api-solid-cache
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=masterpassword123
